name: Robot Framework CI

# on: [push]
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # tHIS IS TO RUN AT 12 (UTC)
  workflow_dispatch: # Manual Run button will be shown if we added this

jobs:
  robot-test:
    runs-on: ubuntu-latest

# --- New Part ---
    strategy:
      matrix:
        browser: [chrome, firefox] # Listed 2 Browser names
# --------------

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     #- name: Install Python and Robot Framework
      #  run: |
       #   python -m pip install --upgrade pip
        #  pip install robotframework robotframework-seleniumlibrary 
        
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

   #   - name: Run Robot Framework Tests
   #     run: robot google_test.robot

      - name: Run Robot Tests with Secret
        env:
          LOGIN_PASSWORD: ${{ secrets.MY_PASSWORD }} # Calling password from Secret
        run: |
          robot --variable DB_PASSWORD:$LOGIN_PASSWORD google_test.robot

      - name: Run Robot Tests
        run: |
          robot --variable BROWSER:headless${{ matrix.browser }} google_test.robot
 #  ${{ matrix.browser }} will take each name from above listed browser

#      - name: Upload Test Report
#        if: always() # Report will be saved whether test is passed or failed
#        uses: actions/upload-artifact@v4
#        with:
#          name: robot-framework-report
#          path: |
#            report.html
#            log.html
#            output.xml

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Need to add matrix.browser to save with different report names
          name: report-${{ matrix.browser }}
          path: |
            report.html
            log.html

      - name: Notify on Failure
        if: failure() # This step will do when some test fails
        run: |
          echo "Test Failed. Please Check Reports"
          
      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # the automatic token given by github
          publish_dir: . # the place where report files are
          publish_branch: gh-pages # the new branch to save reports
          commit_message: "Update Test Report" 

    
          


     
