name: Robot Framework CI

# on: [push]
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # tHIS IS TO RUN AT 12 (UTC)

jobs:
  robot-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     #- name: Install Python and Robot Framework
      #  run: |
       #   python -m pip install --upgrade pip
        #  pip install robotframework robotframework-seleniumlibrary 
        
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

   #   - name: Run Robot Framework Tests
   #     run: robot google_test.robot

      - name: Run Robot Tests with Secret
        env:
          LOGIN_PASSWORD: ${{ secrets.MY_PASSWORD }} # Calling password from Secret
        run: |
          robot --variable DB_PASSWORD:$LOGIN_PASSWORD google_test.robot

      - name: Upload Test Report
        if: always() # Report will be saved whether test is passed or failed
        uses: actions/upload-artifact@v4
        with:
          name: robot-framework-report
          path: |
            report.html
            log.html
            output.xml

     
